# Default initial positions for robotic_arm's ros2_control fake system

initial_positions:
  pitch_joint_1: 0
  pitch_joint_2: 0
  pitch_joint_3: 0
  roll_joint_1: 0
  roll_joint_2: 0
  shift_joint: 0
  yaw_joint_1: 0